# Generated by Django 4.0.8 on 2022-11-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_fish',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_phish_song',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
