# Generated by Django 4.0.7 on 2022-11-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_favorite_fish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_phish_song',
            field=models.TextField(blank=True, null=True),
        ),
    ]
