# Generated by Django 4.0.7 on 2022-11-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_image_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagefile',
            field=models.FileField(blank=True, null=True, upload_to='media/images/', verbose_name=''),
        ),
    ]
